Repository dlang-community/D-YAML, pull requests merged in 2018-05, with the labels that each got.

#131 make the unittests much less noisy by default
  source/dyaml/constructor.d
  source/dyaml/flags.d
  source/dyaml/hacks.d
  source/dyaml/loader.d
  source/dyaml/node.d
  source/dyaml/reader.d
  source/dyaml/resolver.d
  source/dyaml/stream.d
  source/dyaml/test/common.d
  source/dyaml/test/compare.d
  source/dyaml/test/constructor.d
  source/dyaml/test/emitter.d
  source/dyaml/test/errors.d
  source/dyaml/test/inputoutput.d
  source/dyaml/test/reader.d
  source/dyaml/test/representer.d
  source/dyaml/test/resolver.d
  source/dyaml/test/tokens.d
Labels: auto-merge, enhancement

#133 mark Queue as @safe
  source/dyaml/queue.d
Labels: auto-merge

#134 Update Meson build version to tag version.
  meson.build
Labels: auto-merge

#127 improve benchmark subpackage
  examples/yaml_bench/yaml_bench.d
Labels: auto-merge, enhancement

#115 Remove redundant functions
  meson.build
  source/dyaml/constructor.d
  source/dyaml/emitter.d
  source/dyaml/fastcharsearch.d
  source/dyaml/loader.d
  source/dyaml/nogcutil.d
  source/dyaml/parser.d
  source/dyaml/queue.d
  source/dyaml/reader.d
  source/dyaml/representer.d
  source/dyaml/resolver.d
  source/dyaml/scanner.d
  source/dyaml/serializer.d
  source/dyaml/unused.d
Labels: auto-merge

#124 make Loader interface a bit more consistent
  examples/constructor/main.d
  examples/getting_started/main.d
  examples/resolver/main.d
  examples/yaml_bench/yaml_bench.d
  examples/yaml_gen/yaml_gen.d
  examples/yaml_stats/yaml_stats.d
  source/dyaml/constructor.d
  source/dyaml/hacks.d
  source/dyaml/loader.d
  source/dyaml/resolver.d
  source/dyaml/stream.d
  source/dyaml/test/compare.d
  source/dyaml/test/constructor.d
  source/dyaml/test/emitter.d
  source/dyaml/test/errors.d
  source/dyaml/test/inputoutput.d
  source/dyaml/test/representer.d
  source/dyaml/test/resolver.d
  source/dyaml/test/tokens.d
Labels: auto-merge-squash, enhancement

#140 replace CHANGES.rst and README.rst with markdown equivalents
  CHANGES.html
  CHANGES.rst
  README.html
  README.md
  README.rst
Labels: auto-merge-squash

#141 let buildMsg automatically be inferred @safe
  source/dyaml/scanner.d
Labels: auto-merge

#142 convert dyaml.constructor unittests into examples
  source/dyaml/constructor.d
Labels: auto-merge
