Repository dlang-community/D-YAML, pull requests merged in 2018-06, with the labels that each got.

#147 Remove redundant package visibility declarations
  source/dyaml/node.d
Labels: auto-merge

#144 allow uninitialized nodes to become sequence/mapping nodes
  source/dyaml/node.d
Labels: auto-merge

#145 simplify Node.allowed
  source/dyaml/node.d
Labels: auto-merge

#146 Merge Node constructors
  source/dyaml/node.d
Labels: auto-merge-squash

#149 Update tinyendian to 0.2.0
  dub.json
  source/dyaml/reader.d
Labels: auto-merge

#151 make dyaml.reader.countASCII @safe
  source/dyaml/reader.d
Labels: auto-merge

#152 clean up some opAssigns
  source/dyaml/node.d
Labels: auto-merge

#156 fix mardown table not well displayed on DUB website
  README.md
Labels: auto-merge, trivial

#155 remove redundant implicit_2
  source/dyaml/emitter.d
  source/dyaml/event.d
  source/dyaml/parser.d
  source/dyaml/serializer.d
  source/dyaml/test/emitter.d
Labels: auto-merge-squash

#159 style, address D-Scanner warnings on resolver.d, also fix some DDOC stuff
  source/dyaml/resolver.d
Labels: auto-merge, trivial

#158 style, address D-Scanner warnings on scanner.d
  source/dyaml/scanner.d
Labels: auto-merge, trivial

#160 style, address D-Scanner warnings on event.d
  source/dyaml/event.d
Labels: auto-merge, trivial

#162 clean up aliases
  source/dyaml/constructor.d
  source/dyaml/emitter.d
  source/dyaml/exception.d
  source/dyaml/node.d
  source/dyaml/test/common.d
  source/dyaml/test/inputoutput.d
  source/dyaml/token.d
Labels: auto-merge

#161 make the queue fully nogc and optimize it with a freelist
  source/dyaml/queue.d
Labels: auto-merge-squash, optimization

#163 add File overload for Loader.fromFile
  source/dyaml/loader.d
Labels: auto-merge-squash

#164 Remove a number of unsafe immutable casts
  source/dyaml/composer.d
  source/dyaml/dumper.d
  source/dyaml/loader.d
  source/dyaml/parser.d
  source/dyaml/test/common.d
  source/dyaml/test/constructor.d
  source/dyaml/test/emitter.d
  source/dyaml/test/inputoutput.d
  source/dyaml/test/reader.d
Labels: auto-merge-squash

#166 make Dumper.dump @safe
  source/dyaml/dumper.d
Labels: auto-merge

#168 Use Appender for stacks
  source/dyaml/dumper.d
  source/dyaml/emitter.d
  source/dyaml/parser.d
  source/dyaml/scanner.d
Labels: auto-merge

#169 make rest of dyaml.scanner @safe
  source/dyaml/scanner.d
Labels: auto-merge

#170 partially address D-Scanner warnings in the whole project
  source/dyaml/constructor.d
  source/dyaml/dumper.d
  source/dyaml/emitter.d
  source/dyaml/loader.d
  source/dyaml/node.d
  source/dyaml/parser.d
  source/dyaml/reader.d
  source/dyaml/scanner.d
  source/dyaml/serializer.d
  source/dyaml/test/common.d
  source/dyaml/test/constructor.d
  source/dyaml/test/emitter.d
Labels: auto-merge

#150 add Loader.opApply overload for @safe delegates
  source/dyaml/loader.d
Labels: auto-merge

#171 add tojson subpackage for converting yaml docs to json
  .travis.yml
  dub.json
  examples/tojson/dub.json
  examples/tojson/source/app.d
Labels: auto-merge-squash

#172 convert toEscapes AA to a switch for faster convertion
  source/dyaml/emitter.d
  source/dyaml/escapes.d
Labels: auto-merge, enhancement

#154 Replace stream-based dumping interface with an outputrange-based interface
  examples/getting_started/main.d
  examples/representer/main.d
  examples/yaml_bench/yaml_bench.d
  examples/yaml_gen/yaml_gen.d
  meson.build
  source/dyaml/dumper.d
  source/dyaml/emitter.d
  source/dyaml/event.d
  source/dyaml/loader.d
  source/dyaml/node.d
  source/dyaml/parser.d
  source/dyaml/representer.d
  source/dyaml/serializer.d
  source/dyaml/stream.d
  source/dyaml/test/emitter.d
  source/dyaml/test/inputoutput.d
  source/dyaml/test/representer.d
Labels: auto-merge-squash

#174 Update the tinyendian ersion number. Update the D-YAML version number.
  meson.build
Labels: auto-merge
