Repository dlang-community/D-YAML, pull requests merged in 2018-08, with the labels that each got.

#191 fix #190 - Possible broken link #190
  README.md
  source/dyaml/constructor.d
Labels: auto-merge, trivial

#197 some dub.json cleanup, add self to authors, update copyright
  dub.json
Labels: auto-merge

#198 use camelCasing for enum members
  source/dyaml/composer.d
  source/dyaml/dumper.d
  source/dyaml/emitter.d
  source/dyaml/event.d
  source/dyaml/hacks.d
  source/dyaml/linebreak.d
  source/dyaml/node.d
  source/dyaml/parser.d
  source/dyaml/representer.d
  source/dyaml/resolver.d
  source/dyaml/scanner.d
  source/dyaml/serializer.d
  source/dyaml/style.d
  source/dyaml/test/common.d
  source/dyaml/test/emitter.d
  source/dyaml/test/tokens.d
  source/dyaml/token.d
Labels: auto-merge

#199 eliminate @trusted hack in dyaml.emitter
  source/dyaml/emitter.d
Labels: auto-merge-squash
