Repository dlang-community/D-YAML, pull requests merged in 2018-07, with the labels that each got.

#177 Remove dyaml.flags, Use std.typecons.BitFlags
  meson.build
  source/dyaml/emitter.d
  source/dyaml/flags.d
Labels: auto-merge-squash

#178 remove some refs to YStream
  source/dyaml/emitter.d
Labels: auto-merge

#180 Some YAMLObject simplification
  source/dyaml/node.d
Labels: trivial

#176 Rangify parser
  source/dyaml/composer.d
  source/dyaml/dumper.d
  source/dyaml/loader.d
  source/dyaml/parser.d
  source/dyaml/test/compare.d
  source/dyaml/test/emitter.d
Labels: auto-merge-squash

#182 \s\body\do
  source/dyaml/dumper.d
  source/dyaml/loader.d
  source/dyaml/node.d
  source/dyaml/test/common.d
Labels: auto-merge, trivial

#185 a handful of DIP1000 fixes
  source/dyaml/emitter.d
  source/dyaml/node.d
  source/dyaml/reader.d
Labels: auto-merge-squash

#186 don't throw away file/line when throwing new YAMLExceptions
  source/dyaml/dumper.d
  source/dyaml/loader.d
Labels: auto-merge

#188 fix windows/mac linebreaks
  source/dyaml/dumper.d
  source/dyaml/linebreak.d
Labels: auto-merge
