Repository dlang-community/D-YAML, pull requests merged in 2019-01, with the labels that each got.

#210 add scope to some emitter functions that need it
  source/dyaml/emitter.d
Labels: auto-merge, trivial

#212 fix UTF-8 decoding in URI sequences
  source/dyaml/scanner.d
  source/dyaml/test/resolver.d
  test/data/uri.data
  test/data/uri.detect
Labels: Bug Fix, auto-merge

#209 add an official yaml test suite runner
  .travis.yml
  dub.json
  testsuite/dub.json
  testsuite/source/app.d
Labels: auto-merge-squash

#214 Add codecov badge to readme
  README.md
Labels: auto-merge-squash, trivial

#216 remove deprecated Loader.loadAll()
  source/dyaml/loader.d
Labels: auto-merge-squash

#217 update documentation
  docs/tutorials/getting_started.md
  docs/tutorials/yaml_syntax.md
Labels: auto-merge-squash

#213 Move custom types to Node
  docs/tutorials/custom_types.md
  examples/constructor/main.d
  examples/representer/main.d
  examples/resolver/main.d
  examples/yaml_bench/yaml_bench.d
  source/dyaml/composer.d
  source/dyaml/constructor.d
  source/dyaml/dumper.d
  source/dyaml/loader.d
  source/dyaml/node.d
  source/dyaml/package.d
  source/dyaml/representer.d
  source/dyaml/scanner.d
  source/dyaml/test/constructor.d
  source/dyaml/test/emitter.d
  source/dyaml/test/representer.d
  source/dyaml/test/resolver.d
  test/data/empty-python-module.loader-error
  test/data/empty-python-name.loader-error
  test/data/undefined-constructor.loader-error
Labels: auto-merge-squash, enhancement

#218 convert the composer to a struct
  source/dyaml/composer.d
  source/dyaml/loader.d
Labels: auto-merge-squash

#223 Remove tagcmp
  source/dyaml/node.d
  source/dyaml/test/constructor.d
  source/dyaml/test/representer.d
Labels: Bug Fix, auto-merge-squash
